version: '3'

dotenv: ['custom.env', 'default.env']

vars:
  AWESOME_FILE: ../data/README.md
  BASE_IRI: https://aksw.org/Projects/
  OUTPUT: ../graph/
  NT: ../data/aksw.org.nt

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  md:gen:
    desc: Generate Markdown file
    cmds:
      - python3 ./data/extract_script.py {{.URL}}


  install:
    desc: Install the dependencies with poetry
    cmds:
      - poetry install

  run:
    desc: Execute the command
    cmds:
      - poetry run python3 -m waag.cli --awesome-file {{.AWESOME_FILE}} --iri {{.BASE_IRI}} --output-dir {{.OUTPUT}} --graph-nt {{.NT}}

  test:
    desc: Run tests
    cmds:
      - poetry run pytest

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix


